// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_gameboard.cpp"
#include "EWIEGA46WW/moc_gameoverdialog.cpp"
#include "EWIEGA46WW/moc_namedialog.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
